from typing import Sequence

from .ev import *

_EventId = tuple[int, int]
_EventSpec = _EventId | tuple[int, int, int, int, int, int]

class Device:
    def __init__(
        self,
        events: Sequence[_EventSpec],
        name: str = ...,
        bustype: int = ...,
        vendor: int = ...,
        product: int = ...,
        version: int = ...,
        fd: int | None = ...,
    ) -> None: ...
    def syn(self) -> None: ...
    def emit(self, event: _EventId, value: int, syn: bool = ...) -> None: ...
    def emit_click(self, event: _EventId, syn: bool = ...) -> None: ...
    def emit_combo(self, events: Sequence[_EventId], syn: bool = ...) -> None: ...
    def destroy(self) -> None: ...
    def __enter__(self) -> "Device": ...
    def __exit__(self, *args: object) -> bool: ...
